spring:
  profiles:
    active: 
    - dev
  

---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-dev
  
---
spring:
  profiles: prod  #开发环境
  application:
    name: microservicecloud-config-prod
    
#保存为utf-8编码    
  