server:
  port: 3355

spring:
  application:
    name: microserver-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:chukun1308/microserver-cloud-config.git #github上面git仓库的地址